# -*- coding: utf-8 -*-
 
# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
 
 
from PyQt5 import QtCore, QtGui, QtWidgets
 
 
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uploaButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploaButton.setGeometry(QtCore.QRect(100, 500, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.uploaButton.setFont(font)
        self.uploaButton.setObjectName("uploaButton")
        self.lblImage = QtWidgets.QLabel(self.centralwidget)
         #self.imageLabel.setGeometry(QtCore.QRect(40, 30, 400, 300))
        self.lblImage.setGeometry(QtCore.QRect(40, 30, 400, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblImage.setFont(font)
        self.lblImage.setScaledContents(True)
        self.lblImage.setObjectName("lblImage")
        self.convertComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.convertComboBox.setGeometry(QtCore.QRect(110, 400, 200, 25))
        self.convertComboBox.setObjectName("convertComboBox")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.convertComboBox.addItem("")
        self.brightnesshorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.brightnesshorizontalSlider.setGeometry(QtCore.QRect(290, 450, 160, 22))
        self.brightnesshorizontalSlider.setMinimumSize(QtCore.QSize(1, 1))
        self.brightnesshorizontalSlider.setMinimum(1)
        self.brightnesshorizontalSlider.setMaximum(100)
        self.brightnesshorizontalSlider.setSliderPosition(50) #7
        self.brightnesshorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnesshorizontalSlider.setObjectName("brightnesshorizontalSlider")
        self.brightnesslabel = QtWidgets.QLabel(self.centralwidget)
        self.brightnesslabel.setGeometry(QtCore.QRect(110, 450, 101, 19))
        self.brightnesslabel.setObjectName("brightnesslabel")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(320, 500, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.contrastlabel = QtWidgets.QLabel(self.centralwidget)
        self.contrastlabel.setGeometry(QtCore.QRect(490, 450, 91, 19))
        self.contrastlabel.setObjectName("contrastlabel")
        self.contrasthorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.contrasthorizontalSlider.setGeometry(QtCore.QRect(610, 450, 160, 22))
        self.contrasthorizontalSlider.setMinimum(1)
        self.contrasthorizontalSlider.setMaximum(100)
        self.contrasthorizontalSlider.setSliderPosition(50)
        self.contrasthorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrasthorizontalSlider.setObjectName("contrasthorizontalSlider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
 
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
 
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Imagetransformer"))
        self.uploaButton.setText(_translate("MainWindow", "Upload Image"))
        self.lblImage.setText(_translate("MainWindow", "Display Image"))
        self.convertComboBox.setItemText(0, _translate("MainWindow", "Convert to Grayscale"))
        self.convertComboBox.setItemText(1, _translate("MainWindow", "Gaussian Blur \n"
""))
        self.convertComboBox.setItemText(2, _translate("MainWindow", "Median Blur \n"
""))
        self.convertComboBox.setItemText(3, _translate("MainWindow", "Sobel Edge Detection"))
        self.convertComboBox.setItemText(4, _translate("MainWindow", "Canny Edge Detection "))
        self.convertComboBox.setItemText(5, _translate("MainWindow", "Thresholding (Binary or Adaptive)"))
        self.convertComboBox.setItemText(6, _translate("MainWindow", "Image Rotation \n"
""))
        self.convertComboBox.setItemText(7, _translate("MainWindow", "Image Resizing "))
        self.convertComboBox.setItemText(8, _translate("MainWindow", "Erosion"))
        self.convertComboBox.setItemText(9, _translate("MainWindow", "Dilation"))
        self.convertComboBox.setItemText(10, _translate("MainWindow", "FlipHorizontal"))
        self.convertComboBox.setItemText(11, _translate("MainWindow", "FlipVertical"))
        self.brightnesslabel.setText(_translate("MainWindow", "Brightnness"))
        self.contrastlabel.setText(_translate("MainWindow", "Contrast"))
        self.saveButton.setText(_translate("MainWindow", "Save Image"))
 
 
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
 